### ISSUE TITLE
Vitess compatibility

### ISSUE THREAD

**Issue by BillyYccc** [BillyYccc/vertx-mysql-client-compatibility-testkit#1]
check compatibility with https://vitess.io/

**Comment by LeeWong** [comment]
Any update on this?

**Comment by BillyYccc** [comment]
Hi, Vitess is compatible with MySQL Client/Server Protocol so generally speaking Reactive MySQL Client should work with Vitess, but there should be some edge cases which it could not handle them well.

I have checked basically that the client should support such [features](https://github.com/BillyYccc/vertx-mysql-client-compatibility-testkit#database-compatibility) with Vitess 4.0(set up a local cluster with docker-compose), I think the whole testkit could add tests for checking more features and we could reuse a part of the [SQL Client TCK](https://github.com/eclipse-vertx/vertx-sql-client/tree/master/vertx-sql-client/src/test/java/io/vertx/sqlclient/tck).

Thanks for your interest I want to ask you a question  :-)
Are you using Vert.x or plan to use MySQL client embeddedly in other applications with Vitess?

**Comment by LeeWong** [comment]
Yes, I am using vert.x and plan to use vertx client to interact with Vitess. What are the edge cases that it cannot handle them?

**Comment by BillyYccc** [comment]
What I mean here is that the client is 'MySQL-oriented' which means it's expected to work in the way MySQL works(if not then it should be fixed), if Vitess behaves differently from what MySQL does then something may be broken, I think the [documentation](https://vitess.io/docs/reference/mysql-compatibility/) has shown some known issues.

**Comment by LeeWong** [comment]
Very true. When using vitess, the application sql queries have to be designed accordingly to avoid those known issues.
